### ISSUE TITLE
fms如何模拟err的情况？

### ISSUE THREAD

**Issue by ouzhongyuan** [nimojs/fms#21]
request对结果没有约束力呀，就算不填写request中的值，也是返回ok

**Comment by ouzhongyuan** [comment]
fms.get('/title', {
    title: "链式调用",
    request: {
        id: 1,
        _id: "Id号"
    }
}).ok({
    msg: "ok"
}).err({
    meg: "err"
});

**Comment by ouzhongyuan** [comment]
fms.get('/title', {
    title: "链式调用",
    request: {
        id: 1,
        _id: "Id号"
    }
}).ok({
    msg: "ok"
}).err({
    meg: "err"
});

**Comment by nimojs** [comment]
可在 [http://demo.fmsjs.org/](/) 或者[http://demo.fmsjs.org/fms/](/fms/) 中通过 select 控制成功失败

**Comment by nimojs** [comment]
![](http://fmsjs.org/static/img/ajax-1.png)

**Comment by nimojs** [comment]
`request` 是用于生成文档中的提交参数说明
---
你还可以通过 m.js 提供的 `fms.res` `fms.btn` 方法控制AJAX响应结果
[m.js文档](http://fmsjs.org/m-js.html)
[m.js 使用示例](http://demo.fms.help/static/m.js.html)
