### ISSUE TITLE
通过fms.view传递的data对象中不能包含函数？

### ISSUE THREAD

**Issue by sunhjie** [nimojs/fms#27]
在后端渲染服务器中得到的data对象中过滤掉了函数

**Comment by nimojs** [comment]
是指
```
template            "news.php"
templateDir         "/Users/nimojs/Documents/git/fms-demo/view/"
templatePath        "/Users/nimojs/Documents/git/fms-demo/view/news.php"
templatePluginDir   "/Users/nimojs/Documents/git/fms-demo/view/plugin/"
data                "{"title":"论数据约定在前后端配合中的重要性"}"
```
中的 data  么？

如果是：POST中是无法保存函数的，跟JSON中无法保存函数一样。

----

请描述一下你的业务场景，我看如何给你个解决方案

**Comment by sunhjie** [comment]
是这个data，我这边后台页面渲染返回的数据有些是带函数的，比如
global.currPage = $!{positions.getCurrentPageNo()};
我用node封装了一个velocity渲染服务器，来渲染并返回渲染后的页面，但是通过fms.view传递过来的data中无法读取出这个后台返回的函数返回值，所以页面无法渲染相关的数据。

所以现在一个想法是，在启动fms的时候就把页面进行渲染并保存到指定的文件夹里，但是这样生成的文档中也是没有函数的。

**Comment by nimojs** [comment]
velocity 的渲染服务器是node版本的？

> 在启动fms的时候就把页面进行渲染并保存到指定的文件夹里
你的意思是将渲染结果HTML保存在一个文件夹里面？

方便github建个项目将示例代码放上去么？

**Comment by nimojs** [comment]
fms关于页面渲染的流程如下：

1.使用 fms.view 配置 /demo/ 页面使用 {a:1} 渲染 demo.tpl

2.访问 /demo/ 后 fms 会向指定渲染服务器发送请求，会附上
```
template            "news.php"
templateDir         "/Users/nimojs/Documents/git/fms-demo/view/"
templatePath        "/Users/nimojs/Documents/git/fms-demo/view/news.php"
templatePluginDir   "/Users/nimojs/Documents/git/fms-demo/view/plugin/"
data                "{"title":"论数据约定在前后端配合中的重要性"}"
```
3. 渲染服务器根据提交参数返回渲染结果
4. fms 在 /demo/ 页面显示对于结果

---
如果你要生成一个文件可以试试  docFile

http://fmsjs.org/doc.html#fms.docFile(path)
