### ISSUE TITLE
fms好像不支持跨域ajax，作为mock，应该支持吧？

### ISSUE THREAD

**Issue by dajbd** [nimojs/fms#28]
没有看到对应的跨域配置。
求解。
tks.

**Comment by dajbd** [comment]
实测，跨域访问--http: 405

**Comment by nimojs** [comment]
感谢PR

**Comment by rujianwang** [comment]
gulp serve的端口 和 fms 的端口不一样，出现跨域问题 请问该怎么解决？

**Comment by nimojs** [comment]
@rujianwang 


比如 gulp端口 1000
fms端口 2000
你是在哪个端口访问页面，需要访问另外一个端口？

先用 `app.run({CORS:true})` 看能不能解决需求
