### ISSUE TITLE
关于URL映射问题

### ISSUE THREAD

**Issue by luqingxuan** [nimojs/fms#37]
我设计了两个API，
url : '/v1/dev/apps/:appId' ，get方法，加载详情，
url : '/v1/dev/apps/:pageNo/:pageSize',get方法，分页查询，
当我执行ajax调用时，http://localhost:8080/v1/dev/apps/3/16，
发现匹配的URL是第一个，实际上我是想调用第二个，
所以想问一下，FMS中，识别的URL不是精确匹配么？

**Comment by nimojs** [comment]
你试着换一下两个 ajax 配置的顺序， REST 部分我是直接调用 express 的 app.use 的

**Comment by nimojs** [comment]
```
这个顺序可以
url: '/user/message/:page'
url: '/user/:id'
```

```
这个顺序只会出现 /user/ 的内容
url: '/user/:id'
url: '/user/message/:page'
```

**Comment by luqingxuan** [comment]
哈哈现在的问题是我的所有ajax配置，每个都是写了单独的js文件，通过扫描文件夹，读取所有的ajax配置，然后统一fms.ajax，顺序没办法保证，这么将来，express也是坑啊，这点上

**Comment by nimojs** [comment]
我想想办法，今天将解决方案发在这里

**Comment by nimojs** [comment]
已将 app.use 改为 app.get app.post
请重新下载 fms 使用
```js
npm install fms
```
